version: 1.0.{build}
image: Visual Studio 2017
nuget:
  project_feed: true
build_script:

- cmd: >-
    msbuild ComputerAlgebra\ComputerAlgebra.csproj

    nuget pack ComputerAlgebra
artifacts:
- path: '*.nupkg'